### ISSUE TITLE
The default size of the window is small

### ISSUE THREAD

**Issue by A3EKV** [spakin/SimpInkScr#12]
Hi,
When I run the extension, the main window looks like this:

![default](https://user-images.githubusercontent.com/90999345/145163390-3c87b6d0-9ad1-4945-8d4c-605623acee3a.png)

As you can see, the window is small and more particularly, the code area is very small and one needs every time he/she opens this extension to resize the window. So every time I open the extension I need to resize the window to something like this:

![after_resize](https://user-images.githubusercontent.com/90999345/145163593-d5ce6574-7404-4433-acae-199372eff998.png)

I hope this gets fixed. 

Thank you

**Comment by spakin** [comment]
This is a "[Goldilocks and the Three Bears](https://en.wikipedia.org/wiki/Goldilocks_and_the_Three_Bears)" sort of issue in that issue #3 complained that the window was too *large*!  (Admittedly, the window was exceedingly tall before I replaced the detailed *Help* tab with a brief *About* tab containing just a GitHub link.)

Simple Inkscape Scripting uses Inkscape's [INX extension descriptor format](https://wiki.inkscape.org/wiki/INX_extension_descriptor_format) to construct its user interface.  Inkscape sets the initial height of the window based on the height of the tallest tab.  It allows the window to be made taller or wider but not shorter or narrower.  As you observed, it does not remember the window's previous size.

Because the issue lies with Inkscape itself rather than Simple Inkscape Scripting's use of Inkscape, I'm going to suggest you [file a bug report with Inkscape](https://gitlab.com/inkscape/inbox/-/issues/), recommending that they store an extension window's size and reuse that size the next time the window is presented.  If you don't mind, please paste a link to the issue number here so others with the same frustration can more easily find the the discussion on Inkscape's bug-tracking site.  Thanks.
