### ISSUE TITLE
text_path results may not be as expected

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#23]
The example script crashes.

![Screenshot 2022-01-01 160422](https://user-images.githubusercontent.com/140737/147861953-11c78965-84ef-474d-9af1-7a0031952fd4.png)

It looks for python 3.9

I am running 3.10.1 on Windows 11

![Screenshot 2022-01-01 161326](https://user-images.githubusercontent.com/140737/147862032-96eaebaf-2bb3-4082-8e8e-aa43dd84bba0.png)

**Comment by spakin** [comment]
From the error message, it looks like the problem is that [`text_path.py`](https://github.com/spakin/SimpInkScr/blob/4de5d30d24e648d595bac5671dac9b720daf8546/examples/text_path.py) was written with standard [UTF-8](https://en.wikipedia.org/wiki/UTF-8) character encoding, but Python on Windows is assuming that the file uses [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) encoding—or there's some similar kind of encoding mismatch.

Is your `text_path.py` unmodified?  I see the following MD5 hash:
```console
$ md5sum examples/text_path.py 
4b44f24c1aa45a4eb1c76b4ad97800cb  examples/text_path.py
```
(If you don't have `md5sum`, I've read that you can enter `certutil -hashfile examples/text_path.py MD5` on Windows, but I don't have convenient access to a Windows system to try that myself.)

**Comment by peterennis** [comment]
Mismatch for MD5

![Screenshot 2022-01-02 140514](https://user-images.githubusercontent.com/140737/147889483-227df15f-4287-482c-9956-e00f46e45f71.png)

**Comment by spakin** [comment]
Do any of the attached versions work?  (I'd be surprised if `text_path-ASCII.py` does not.)

[text_path.zip](https://github.com/spakin/SimpInkScr/files/7799942/text_path.zip)

```console
$ md5sum text_path*.py
82a3b1c72d92213df1ceb832ad92bf60  text_path-ASCII.py
487f04cc8c278480f195eb7816b3dc64  text_path-CP1252.py
4b44f24c1aa45a4eb1c76b4ad97800cb  text_path-UTF8.py
```

**Comment by peterennis** [comment]
![Screenshot 2022-01-03 154815](https://user-images.githubusercontent.com/140737/147988742-9819d106-811f-4a14-8349-1da08f99c1aa.png)

**Comment by spakin** [comment]
So far, so good.  I'm eager to hear which of those run from Simple Inkscape Scripting and which abort with an error message.

**Comment by peterennis** [comment]
![Screenshot 2022-01-03 184126](https://user-images.githubusercontent.com/140737/147998921-695599bf-1002-437f-87a7-b223b82ff193.png)
![Screenshot 2022-01-03 184345](https://user-images.githubusercontent.com/140737/147998923-4cdd0aee-db89-4203-8b5a-236c1a192bfe.png)
![Screenshot 2022-01-03 184559](https://user-images.githubusercontent.com/140737/147998927-a538d582-e157-4a53-bad4-f0376fe94ebf.png)

**Comment by spakin** [comment]
Thanks for running those tests and sharing the results.  That really helps explain where the problem lies.

After pondering a bunch of alternatives of how to handle the different default character encodings between Windows (CP-1252) and Linux/macOS (UTF-8), I believe the best is simply to re-encode `text_path.py` in ASCII but use Python's \u*xxxx* notation to specify Unicode characters.  Please let me know if the attached version of the example works for you.  It should (a) not produce an error message and (b) correctly include curly quotes and an em dash in the text typeset by Inkscape.

[text_path.zip](https://github.com/spakin/SimpInkScr/files/7810516/text_path.zip)

**Comment by peterennis** [comment]
Looks like that fixed it 😃 

![Screenshot 2022-01-05 185815](https://user-images.githubusercontent.com/140737/148316141-9d01b8cd-43c0-4b1c-a749-053fb91bdb35.png)

**Comment by peterennis** [comment]
There should be a note added in the docs/code sample/wiki to
explain this for Windows users.

**Comment by spakin** [comment]
Thanks for testing the revised script.  I committed the [UTF-8-free `text_path.py`](https://github.com/spakin/SimpInkScr/blob/8bc98a9f97becbb54df23b456db8260cc336bcdc/examples/text_path.py) as 8bc98a9f97becbb54df23b456db8260cc336bcdc.

I decided to hold off on discussing encoding issues in the documentation as they're extremely unlikely to occur in practice now that Simple Inkscape Scripting itself is free of non-ASCII characters.  The problem will reoccur only if Windows users and Linux/macOS users exchange Simple Inkscape Scripting scripts _and_ these scripts contain non-ASCII characters.  At some point, I may create a Troubleshooting page in the documentation, and that can include a section on encoding caveats.
