### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#29]
SIS is GPL v3+

This is fine, but it seems to me that using a simple script such as Clear.py (https://github.com/peterennis/SimpInkScr/blob/Synkypy/aepyx/002_Clear.py)
introduces copyleft with a sledgehammer.

I did some research on Python licensing here: https://docs.python.org/3/license.html

The relevant part is:

>Terms and conditions for accessing or otherwise using Python
Python software and documentation are licensed under the PSF License Agreement.
>
>Starting with Python 3.8.6, examples, recipes, and other code in the documentation are dual licensed under the PSF License Agreement and the Zero-Clause BSD license.

While learning Python and SIS it is not clear to me the licensing terms of the wiki examples.

I have some animations here: https://adaept.com/menu/home
and here: https://adaept.com/menu/logae
and here: https://adaept.com/menu/kute

I would like to port some of them to SIS SMIL but remain hesitant
due to the implicit GPL v3+ wiki license.

Please provide some clarification.

**Comment by spakin** [comment]
[IANAL](https://www.acronymfinder.com/I-Am-Not-A-Lawyer-(IANAL).html), but my interpretation of the Python license is that it applies only to "examples, recipes, and other code in the documentation" that are shipped with Python, not to any Python scripts you write.  Likewise, Simple Inkscape Scripting's GPL v3+ license applies to Simple Inkscape Scripting itself (code, examples, documentation), not to any scripts you write *using* SIS.

I don't see any legal issues with your porting your animations to Simple Inkscape Scripting scripts.  As far as I understand the law, those scripts are your intellectual property and no one else has any claim to them.

`Clear.py` is a funny case because it originates from a GitHub issue.  I have no idea how copyrights and licenses apply to issues.  Let's just say that the original code for deleting all SVG shape elements in a document is in the public domain and that you can use it as you see fit.

**Comment by peterennis** [comment]
> Likewise, Simple Inkscape Scripting's GPL v3+ license applies to Simple Inkscape Scripting itself (code, examples, documentation), not to any scripts you write _using_ SIS.

That is clear. I was also referring to the optional BSD0 license for python examples which,
from your clarification, is not an option with SIS.

> Let's just say that the original code for deleting all SVG shape elements in a document is in the public domain and that you can use it as you see fit.

Thanks for that 👍

**Comment by spakin** [comment]
> That is clear. I was also referring to the optional BSD0 license for python examples which, from your clarification, is not an option with SIS.

Ah, so you were asking if the SIS examples could be used without the sticky GPL v3+ license terms applying?  Although I'm not fundamentally opposed to that, I think it's simplest and least ambiguous to have one license apply to all of SIS.
