### ISSUE TITLE
The rotate and scale with anchor set to "center" doesn't work for Polygons/Stars,  Text, and spirals

### ISSUE THREAD

**Issue by SignificantCell2** [spakin/SimpInkScr#35]
Hello,
Sorry, if this doesn't deserve its own issue.

The new `rotate` and  `scale` that accept anchor points work perfectly for different objects such as rectangles, circles, etc.

However, this doesn't seem to work for **Polygons**,  **Stars**,  **text**, or **spirals**.

How to reproduce:

* Create a star (or an polygon, or a **text** or a **spiral**) and select it.
* Run the code:

```
objs = svg_root.selection

for obj in objs:
   obj = inkex_object(obj)
   obj.scale(1.2, around='center')
   #obj.rotate(angle, around='center')

```

**Comment by spakin** [comment]
I haven't been able to reproduce this problem in Inkscape 1.2-dev:

![scaling](https://user-images.githubusercontent.com/650041/150007247-21cc5e09-f59a-4767-a798-1d548e187021.gif)

**Comment by SignificantCell2** [comment]
That's weird. I am using `Inkscape 1.2-dev (c2cb8da, 2022-01-11)` on Ubuntu 20.04.

**Comment by spakin** [comment]
I pulled down today's build (`Inkscape 1.2-dev (ae62f47, 2022-01-18)` on Ubuntu 21.10).  Still no problems:
![rotating](https://user-images.githubusercontent.com/650041/150023481-61dd2414-9aa5-4aae-b3e3-5af63e424830.gif)

**Comment by SignificantCell2** [comment]
I have downloaded the same version as yours (`Inkscape 1.2-dev (ae62f47, 2022-01-18)` on Ubuntu 20.04 both the Appimage and the linux build with deb file). I have of course the latest commit of SimpInkScr, and I have "reset preferences" closed, inkscape, etc. but still having the same issue.

I have no idea what's causing that.
Isn't there any sort of debug mode for SimInkScr?

**Comment by spakin** [comment]
I wonder if it's our respective default templates?  Here's mine: [template.zip](https://github.com/spakin/SimpInkScr/files/7893063/template.zip)

I don't know a good way to debug Inkscape extensions.  My sad approach is to pepper the code with `inkex.utils.debug` calls.

**Comment by SignificantCell2** [comment]
Thank you for sharing your template, I will try it and will report back later.

I have literally changed everything: reset preferences, made sure to delete the templates, preferences files manually, restarting the computer, checking with both numpy 1.21.x and 1.22.x version, etc. and still the same issue. I have also used both the Linux build and the appimage (the last builds) and removed the extension and installed it from scratch.

Even further, I have downloaded Ubuntu 21.10 and tried it on Virtual box, downloaded the latest development AppImage of Inkscape (same as yours) and cloned your repository. But.... still the same issue.

I am clueless, the only option, is to try with your template.

Could you please try the Appimage version of Inkscape?

**Comment by SignificantCell2** [comment]
**UPDATE:**
🤯️ The issue is solved when I used your template. My first guess is this has something to do with default units.🤯️

**Comment by spakin** [comment]
I was able to reproduce the problem!  I tried `width=1024px`, `height=768px`, and `viewBox=0 0 290 210`.  It's bizarre that the problem is shape-specific.  I'll try tracking down the bug, but I suspect it may lie in Inkscape itself given that Simple Inkscape Scripting follows the same code path regardless of shape.

**Comment by spakin** [comment]
The problem seems to involve only shapes for which a transform is defined.  Inkscape apparently includes a transform on spirals, polygons, and stars upon creation.  Your scaling script works fine when I run it on the transform-free shapes in this file: [star-box.zip](https://github.com/spakin/SimpInkScr/files/7919531/star-box.zip).  Do you observe that same behavior?

**Comment by spakin** [comment]
There might be no issue here, after all.  I think you simply need to tell Simple Inkscape Scripting to apply the new transform *before* any existing transform:
```Python
objs = svg_root.selection

for obj in objs:
   obj = inkex_object(obj)
   obj.scale(1.2, around='center', first=True)
   #obj.rotate(angle, around='center', first=True)
```

Does the addition of `first=True` as in the above make the scaling work as expected?

**Comment by SignificantCell2** [comment]
Specifying `first=True` solves the issue. But that's not always obvious
In that case, I think `first=True` should be the default argument.

Another question, why it doesn't fail with your template when `first=False`?

**Comment by spakin** [comment]
> Specifying `first=True` solves the issue. But that's not always obvious
> In that case, I think `first=True` should be the default argument.

I had thought quite a bit about whether the default for `first` should be `True` or `False`.  For *your* use case—modifying existing shapes with unknown transforms applied to them—`first=True` would be a more sensible default.  However, another use case, which I feel may be more common in practice, is shape generation.  In that case, `first=False` makes more sense because it's more natural for the sequence `obj.translate()`…`obj.rotate()`…`obj.scale()` to mean "translate the object, then rotate the translated object, then scale the translated+rotated object" rather than "translate the object; but before you do that, rotate it; oh, and before you do either of those, scale it".

Both use cases are valuable, but I ended up favoring `first=False` as the default so transforms are applied in the order specified in the program.

> Another question, why it doesn't fail with your template when `first=False`?

Ah, it's because there are no transforms in my example.  Applying a transform either before or after the identity transform produces the same result.

**Comment by SignificantCell2** [comment]
It would be very nice to document that in the Wiki as a warning because not all user have a math background, so probably something like this:

```
Warning: Specifying anchor='center' may not result in the expected behaviour if the object has already some transform. Consider using the argument first=True
```

Stating that explicitly would save time for new users that will encounter the issue above.

**Comment by spakin** [comment]
Rather than present this as a warning, I added a section to the wiki page entitled, "[Advice for the use of `first`](https://github.com/spakin/SimpInkScr/wiki/Modifying-existing-objects/a97b8b28a8706d234ffbc31099f13d8209da9036#advice-for-the-use-of-first)" that includes examples of `first=False` and `first=True` each being the more appropriate option.
