### ISSUE TITLE
set method fails silently when the value is numeric

### ISSUE THREAD

**Issue by SignificantCell2** [spakin/SimpInkScr#38]
When using `set` method to change the style of an object, e.g:

```
objs = svg_root.selection
for obj in objs:
   obj.set('width', 50) # <<<<<<< the value is numeric

```

When you run that, nothing changes. Instead the user need to explicitly to convert the value to a string, i.e.:

```
obj.set("width", str(50))
```

SimpIncScr should at least raise an error explictly when the value is numeric or convert it automatically.

**Comment by spakin** [comment]
Simple Inkscape Scripting converts values to strings for all of *its* methods.  The preceding code is bypassing Simple Inkscape Scripting and using [`inkex`](https://inkscape.gitlab.io/extensions/documentation/) directly.  (Okay, Simple Inkscape Scripting is providing an [`inkex.SvgDocumentElement`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.elements._svg.html#inkex.elements._svg.SvgDocumentElement) via `svg_root`, but that doesn't count).  That is, `obj` is an `inkex` object, and the `set` method is implemented by `inkex` (or perhaps the underlying [`lxml`](https://lxml.de/) package—I forgot).  There's nothing Simple Inkscape Scripting can do to help you if you don't invoke its objects' methods.

**Comment by SignificantCell2** [comment]
Hi,
Thanks for clarifying that.
Unfortuately reading the wiki page I still can't find a way to change the width of an object without applying transformations. 

How can I achieve that using SimpInkScr methods?

Thank you

**Comment by spakin** [comment]
> Thanks for clarifying that.
> Unfortuately reading the wiki page I still can't find a way to change the width of an object without applying transformations.
> 
> How can I achieve that using SimpInkScr methods?

This issue got me thinking, and as of 9dd149d3771a82935e68134b5cd3e3d1c99158bf, there's now a way to do it!  You can find documentation on the Simple Inkscape Scripting wiki under [Modifying existing objects](https://github.com/spakin/SimpInkScr/wiki/Modifying-existing-objects), but here's a summary:

* Use `selected_shapes()` instead of `svg_root.selection`.  The former returns Simple Inkscape Scripting objects while the latter returns [`inkex`](https://inkscape.gitlab.io/extensions/documentation/) objects.

* Invoke the `svg_set` method on a Simple Inkscape Scripting object in place of the `set` method on an `inkex` object.  The former is smart about Python data types while the latter requires a string as its value input.  There's also an `svg_get` that can return either an appropriate Python data type or be forced to return a string.

*Id est*,
```Python
objs = selected_shapes()
for obj in objs:
   obj.svg_set('width', 50)
```
should perform as you'd expect.

**Comment by SignificantCell2** [comment]
Thank you for the update
