### ISSUE TITLE
a lot of blinking during animation creation

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#39]
This code:

```
r01 = rect((0, 0), (32, 0), stroke='#2b1100', fill='#ff0000', font_variation_settings='normal', opacity=1, vector_effect='none', fill_opacity=1, fill_rule='evenodd', stroke_width=1, stroke_linecap='butt', stroke_linejoin='miter', stroke_miterlimit=4, stroke_dasharray='none', stroke_dashoffset=0, stroke_opacity=1, _inkscape_stroke='none', stop_color='#000000', stop_opacity=1)
r1 = rect((0, 0), (32, 1024), stroke='#2b1100', fill='#ff0000', font_variation_settings='normal', opacity=1, vector_effect='none', fill_opacity=1, fill_rule='evenodd', stroke_width=1, stroke_linecap='butt', stroke_linejoin='miter', stroke_miterlimit=4, stroke_dasharray='none', stroke_dashoffset=0, stroke_opacity=1, _inkscape_stroke='none', stop_color='#000000', stop_opacity=1)
r01.animate([r1], duration='2s')

r02 = rect((1024, 32), (1024, 0), stroke='#2b1100', fill='#ff0000', font_variation_settings='normal', opacity=1, vector_effect='none', fill_opacity=1, fill_rule='evenodd', stroke_width=1, stroke_linecap='butt', stroke_linejoin='miter', stroke_miterlimit=4, stroke_dasharray='none', stroke_dashoffset=0, stroke_opacity=1, _inkscape_stroke='none', stop_color='#000000', stop_opacity=1)
r2 = rect((0, 0), (1024, 32), stroke='#2b1100', fill='#ffff00', font_variation_settings='normal', opacity=1, vector_effect='none', fill_opacity=1, fill_rule='evenodd', stroke_width=1, stroke_linecap='butt', stroke_linejoin='miter', stroke_miterlimit=4, stroke_dasharray='none', stroke_dashoffset=0, stroke_opacity=1, _inkscape_stroke='none', stop_color='#000000', stop_opacity=1)
r02.animate([r2], duration='2s', begin_time='2s',)
```

This blinking:

![Blinking](https://user-images.githubusercontent.com/140737/151912455-5190bcf0-c30a-4c0f-83e1-c6c752117d8f.gif)

This svg animation result:

![rectangles-animation2](https://user-images.githubusercontent.com/140737/151912669-3069068a-2e31-4c0f-b412-15386fbdabce.svg)

1. Is the blinking expected? It gets longer as the animation increases.
2. Can it be reduced? Replaced with a progress bar? Just use ........ progress instead?
3. How can I do something similar to:
r02 = rect((1024, 32), (1024, 0), f(get-the-settings())
where get-the-settings returns the string of values?

**Comment by spakin** [comment]
> 1. Is the blinking expected? It gets longer as the animation increases.
> 2. Can it be reduced? Replaced with a progress bar? Just use ........ progress instead?

I don't see any blinking on my system (Ubuntu 21.10).  I tried both Inkscape 1.1.1 and Inkscape 1.2-dev.  In any case, this is an Inkscape issue, not a Simple Inkscape Scripting issue.  The Inkscape core, not the extension, displays the "working, please wait…" dialog box.

> 3. How can I do something similar to:
> r02 = rect((1024, 32), (1024, 0), f(get-the-settings())
> where get-the-settings returns the string of values?

In Python, prefixing a dictionary with `**` expands the dictionary into *key*=*value* arguments.  Hence, something like
```Python
my_style = {'stroke': '#2b1100', 'fill': '#ff0000', 'font_variation_settings': 'normal', 'opacity': 1, 'vector_effect': 'none', 'fill_opacity': 1, 'fill_rule': 'evenodd', 'stroke_width': 1, 'stroke_linecap': 'butt', 'stroke_linejoin': 'miter', 'stroke_miterlimit': 4, 'stroke_dasharray': 'none', 'stroke_dashoffset': 0, 'stroke_opacity': 1, '_inkscape_stroke': 'none', 'stop_color': '#000000', 'stop_opacity': 1}
r02 = rect((1024, 32), (1024, 0), **my_style)
```
should work.  Although I wouldn't recommend it, if you really want to work with strings rather than dictionaries, you can use [`inkex.Style`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.styles.html#inkex.styles.Style) to convert from a style string to a dictionary.

See also Simple Inkscape Scripting's [`style`](https://github.com/spakin/SimpInkScr/wiki/Changing-defaults/ff7589deeb37ccd10a4e64b18ec106ca012cf152#styles) function, which lets you set the default style.  With `style` you can set the attributes that are common to all shapes then override only those you want to change on a per-shape basis by passing appropriate parameters to the shape-construction function.

**Comment by peterennis** [comment]
Reported here: https://gitlab.com/inkscape/inbox/-/issues/6311

**Comment by spakin** [comment]
Thanks for submitting that bug report to Inkscape.  I hope they can fix the problem.
