### ISSUE TITLE
Better Documentation for Path Commands

### ISSUE THREAD

**Issue by alexporth** [spakin/SimpInkScr#52]
I am trying to use the path command but I cannot make head nor tails of the arguments listed in the documentation.
I would greatly appreciate it if the arguments for each of the path commands could be described.
For Example: `Arc(rx, ry, x_axis_rotation, large_arc, sweep, x, y)`
https://inkscape.gitlab.io/extensions/documentation/source/inkex.paths.html?highlight=arc#inkex.paths.Arc
From the documentation, I don't even know which types the arguments expect. Or is there a part of the documentation that I missed where these are described?

**Comment by spakin** [comment]
The trick is to search the Web for SVG documentation, not Inkscape or `inkex` documentation.  I usually start with [MDN Web Docs](https://developer.mozilla.org/).  In the case of arcs, https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#arcs covers SVG's arc (`A`) path subcommand.

I consider arcs by far the hardest SVG path subcommand to understand.  Here's a quick summary:

* It's assumed the arc will begin where the previous path subcommand ended.  Use a `Move` subcommand to set explicit starting coordinates.
* An arc is a partial ellipse.  `rx` and `ry` specify the *x* and *y* radii of that ellipse.
* The ellipse can be rotated by `x_axis_rotation` degrees.
* Ignoring the next two parameters for now, the final parameters, `x` and `y`, specify the ending coordinates of the arc.

Going back to `large_arc` and `sweep`, these arguments are each either `0` or `1`.  They exist because there are in fact *four* arcs that start at position *A*, end at position *B*, and lie on an ellipse with the specified radii and rotation:

![svg-arcs](https://user-images.githubusercontent.com/650041/173204538-15034f60-8c49-4371-81e2-b36482c797ac.png)

A `large_arc` of `1` indicates that you want to go the long route around the ellipse (≥180°) instead of the short way (≤180°), indicated with `0`.  A `sweep` of `0` or `1` selects one of the two possible ellipses to follow.

I hope that helps.

**Comment by alexporth** [comment]
Helps a lot thank you.
